# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest
  
stages:
- stage: TarCovertion
  displayName: Covert to Tar
  jobs:
  - job: TarCovertion
    steps:
    
    - task: Maven@4
      displayName: Build Testsuite 
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: true
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        goals: 'package'
        options: '-Dmaven.test.failure.ignore=true' 
    - task: Bash@3
      displayName: Covert to Tar
      inputs:
        targetType: 'inline'
        script: |
          cd /home/vsts/work/1/s/
          tar -cvf testsuite.tar --directory=. *
          
    - task: ArtifactoryGenericUpload@2
      displayName: upload tar to JFrog
      inputs:
        artifactoryService: 'JFrogServiceConnectionNew'
        specSource: 'taskConfiguration'
        fileSpec: |
          {
            "files": [
              {
                "pattern": "$(Pipeline.Workspace)/*.tar",
                "target": "libs-snapshot-local"
              }
            ]
          }
        collectBuildInfo: true
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'
        failNoOp: true
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          pwd
          mkdir untarfolder
          mkdir tarfolder
  
    - task: ArtifactoryGenericDownload@3
      displayName: Download tar from JFrog
      inputs:
        connection: 'JFrogServiceConnectionNew'
        specSource: 'taskConfiguration'
        fileSpec: |
          {
            "files": [
              {
                "pattern": "libs-snapshot-local/*.tar",
                "target": "/home/vsts/work/1/s/tarfolder/"
              }
            ]
          }
        collectBuildInfo: true
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'
        failNoOp: true

    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          tar -xvf /home/vsts/work/1/s/tarfolder/testsuite.tar -C /home/vsts/work/1/s/untarfolder
          echo "Display tar File"
          ls /home/vsts/work/1/s/tarfolder
          echo "Display Untar File"
          ls /home/vsts/work/1/s/untarfolder
          
          
    