# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest
  
stages:
- stage: TarCovertion
  displayName: Covert to Tar
  jobs:
  - job: TarCovertion
    steps:
    
    - task: Maven@4
      displayName: Build Testsuite 
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: true
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
        goals: 'package'
        options: '-Dmaven.test.failure.ignore=true' 
    - task: Bash@3
      displayName: Covert to Tar
      inputs:
        targetType: 'inline'
        script: |
          cd /home/vsts/work/1/s/
          tar -cvf testsuite.tar --directory=. *
          pwd
          mkdir untarfolder
          mkdir tarfolder
    - task: CopyFiles@2
      inputs:
        Contents: '*.tar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
 
    - task: UniversalPackages@0
      displayName: Publish the TAR file to feed
      inputs:
        command: 'publish'
        publishDirectory: '$(Build.ArtifactStagingDirectory)'
        feedsToUsePublish: 'internal'
        vstsFeedPublish: '18c872ec-cca1-465c-8997-d91402298e49/bbd4590d-d732-49e2-891a-5ab52345f8cd'
        vstsFeedPackagePublish: 'testsuite.tar'
        versionOption: 'patch'
        packagePublishDescription: 'publish tar to azure feed'
      name: getPackageVersion  # Set a unique name for this step
          
    - task: UniversalPackages@0
      displayName: Download the TAR file from feed
      inputs:
        command: 'download'
        downloadDirectory: '$(System.DefaultWorkingDirectory)/tarfolder'
        feedsToUse: 'internal'
        vstsFeed: '18c872ec-cca1-465c-8997-d91402298e49/bbd4590d-d732-49e2-891a-5ab52345f8cd'
        vstsFeedPackage: '2392dfaf-1c23-40a5-a829-e75d0104a0fa'
        vstsPackageVersion: '*'
    - task: Bash@3
      displayName: Display Folder with untar files
      inputs:
        targetType: 'inline'
        script: |
          tar -xvf $(System.DefaultWorkingDirectory)/tarfolder/testsuite.tar -C $(System.DefaultWorkingDirectory)/untarfolder
          echo "Display tar File"
          ls $(System.DefaultWorkingDirectory)/tarfolder
          echo "Display Untar File"
          ls $(System.DefaultWorkingDirectory)/untarfolder
          
          
    