# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

# variables:
# - name: repositoryname
#   value: cucumberNew-libs-snapshot
  
stages:
- stage: TarCovertion
  displayName: TarCovertion
  jobs:
  - job: TarCovertion
    steps:
  
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          pwd
          
          # current_directory=$(pwd)

          # echo "Current Directory: $current_directory"
          
          # tar -cvf testsuite.tar .
    