# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

# variables:
# - name: repositoryname
#   value: cucumberNew-libs-snapshot
  
stages:
- stage: TarCovertion
  displayName: Covertion to Tar
  jobs:
  - job: TarCovertion
    steps:
  
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd /home/vsts/work/1/s/
          tar -cvf testsuite.tar .
          ls
          
    - task: ArtifactoryGenericUpload@2
      displayName: upload tar to JFrog
      inputs:
        artifactoryService: 'JFrogServiceConnectionNew'
        specSource: 'taskConfiguration'
        fileSpec: |
          {
            "files": [
              {
                "pattern": "$(Pipeline.Workspace)/*.tar",
                "target": "qatest-new-1"
              }
            ]
          }
        collectBuildInfo: true
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'
        projectKey: 'qatest'
        failNoOp: true

        
    